DEFAULT_TRANSACTION_AWAITING_POLLING_TIMEOUT_IN_MILLISECONDS = 6000
DEFAULT_TRANSACTION_AWAITING_TIMEOUT_IN_MILLISECONDS = 15 * DEFAULT_TRANSACTION_AWAITING_POLLING_TIMEOUT_IN_MILLISECONDS
DEFAULT_TRANSACTION_AWAITING_PATIENCE_IN_MILLISECONDS = 3000

DEFAULT_ACCOUNT_AWAITING_POLLING_TIMEOUT_IN_MILLISECONDS = 6000
DEFAULT_ACCOUNT_AWAITING_TIMEOUT_IN_MILLISECONDS = 15 * DEFAULT_TRANSACTION_AWAITING_POLLING_TIMEOUT_IN_MILLISECONDS
DEFAULT_ACCOUNT_AWAITING_PATIENCE_IN_MILLISECONDS = 0

<<<<<<< HEAD
BASE_USER_AGENT = "dharitri-py-sdk-py"
=======
BASE_USER_AGENT = "dharitri-py-sdk"
>>>>>>> main
UNKNOWN_CLIENT_NAME = "unknown"
ONE_SECOND_IN_MILLISECONDS = 1000
